export interface SendTask {
  Questions: number;
  Book: "1" | "2";
  Module:
    | "All About Me"
    | "Free Time"
    | "Holidays"
    | "My Town"
    | "School Subjects"
    | "Media"
    | "Paris"
    | "Talents"
    | "Where I live";
  Section:
    | "Eyes and hair"
    | "High-frequency words"
    | "Me and other people"
    | "My self-portrait"
    | "Opinions"
    | "Computers and mobile phones"
    | "Frequency"
    | "High-frequency words"
    | "Sport"
    | "What do they do?"
    | "What do you do?"
    | "What do you like doing?"
    | "When?"
    | "At the café"
    | "Family holidays"
    | "High-frequency words"
    | "I get myself ready"
    | "Numbers and money"
    | "What are you going to do?"
    | "What are your dreams?"
    | "Attractions"
    | "Directions"
    | "Expressions of frequency"
    | "Hi there!"
    | "Opinions"
    | "What can you do at/in … ?"
    | "Where I live"
    | "High-frequency words"
    | "Opinions"
    | "Reasons"
    | "School subjects"
    | "The school day"
    | "The timetable"
    | "What do you eat?/What are you eating?"
    | "What time is it?"
    | "Clothes"
    | "Colours"
    | "High-frequency words"
    | "In the future"
    | "Interjections"
    | "Music"
    | "My character"
    | "Opinions"
    | "Relationships"
    | "Style"
    | "Films"
    | "High-frequency words"
    | "Last night"
    | "On TV"
    | "On the internet"
    | "Opinions"
    | "What are you reading?"
    | "A journey"
    | "High-frequency words"
    | "How did you travel?"
    | "In Paris"
    | "Tourist information"
    | "What was it like?"
    | "When?"
    | "Who stole the Mona Lisa?"
    | "Dreams and ambitions"
    | "Getting ready for the contest"
    | "Giving instructions and advice"
    | "High-frequency words"
    | "The talent contest"
    | "Who's the best?"
    | "Adjectives"
    | "Breakfast"
    | "Evening meal"
    | "Food shopping"
    | "Furniture and appliances"
    | "High-frequency words"
    | "Homes"
    | "Prepositions"
    | "Quantities"
    | "Rooms";
  FrenchToEnglish: boolean;
  DueDate: number;
}

export interface RecieveTask {
    QuestionsLeft: any;
    Questions: number;
    Book: "1" | "2";
    Module:
      | "All About Me"
      | "Free Time"
      | "Holidays"
      | "My Town"
      | "School Subjects"
      | "Media"
      | "Paris"
      | "Talents"
      | "Where I live";
    Section:
      | "Eyes and hair"
      | "High-frequency words"
      | "Me and other people"
      | "My self-portrait"
      | "Opinions"
      | "Computers and mobile phones"
      | "Frequency"
      | "High-frequency words"
      | "Sport"
      | "What do they do?"
      | "What do you do?"
      | "What do you like doing?"
      | "When?"
      | "At the café"
      | "Family holidays"
      | "High-frequency words"
      | "I get myself ready"
      | "Numbers and money"
      | "What are you going to do?"
      | "What are your dreams?"
      | "Attractions"
      | "Directions"
      | "Expressions of frequency"
      | "Hi there!"
      | "Opinions"
      | "What can you do at/in … ?"
      | "Where I live"
      | "High-frequency words"
      | "Opinions"
      | "Reasons"
      | "School subjects"
      | "The school day"
      | "The timetable"
      | "What do you eat?/What are you eating?"
      | "What time is it?"
      | "Clothes"
      | "Colours"
      | "High-frequency words"
      | "In the future"
      | "Interjections"
      | "Music"
      | "My character"
      | "Opinions"
      | "Relationships"
      | "Style"
      | "Films"
      | "High-frequency words"
      | "Last night"
      | "On TV"
      | "On the internet"
      | "Opinions"
      | "What are you reading?"
      | "A journey"
      | "High-frequency words"
      | "How did you travel?"
      | "In Paris"
      | "Tourist information"
      | "What was it like?"
      | "When?"
      | "Who stole the Mona Lisa?"
      | "Dreams and ambitions"
      | "Getting ready for the contest"
      | "Giving instructions and advice"
      | "High-frequency words"
      | "The talent contest"
      | "Who's the best?"
      | "Adjectives"
      | "Breakfast"
      | "Evening meal"
      | "Food shopping"
      | "Furniture and appliances"
      | "High-frequency words"
      | "Homes"
      | "Prepositions"
      | "Quantities"
      | "Rooms";
    FrenchToEnglish: boolean;
    DueDate: number;
    SetBy: string;
    SetOn: number;
    Id: string;
    Username: string;
    Status: "Not Started" | "In Progress" | "Completed";
  }
  